### PR TITLE
fixing console prompting y/n/c for token regeneration

### LINKED ISSUE #5: token refresh only prompts to console
I am trying to load a token on a shiny app, but once it times out token refresh does not work as the console must be reached. 

Can you make the default to TRUE for do_refresh or at least provide an option to change this to true?

function (reason, error_message) 
{
  inform(sprintf("%s. Error message: \n\n", reason))
  inform(error_message$message)
  inform("\n")
  do_refresh <- askYesNo("Would you like to generate a new token?", 
    default = FALSE, prompts = c("y", "n", "c"))
  if (do_refresh & !is.na(do_refresh)) {
    inform("Trying to generate a new token...")
    .fitbitr_token$init_credentials()
  }
  else {
    abort("No token was found, and a new one was not generated.")
  }
  invisible()
}

### PR DESCRIPTION
**Pull request by cstephens32**
Closes #5 

update to ask yes no to default to TRUE to not require console prompt

### CODE REVIEW

**Comment by mrkaye97** [comment]
thanks for the contribution @cstephens32! have you tested this from your fork? and if so, does it solve your auth issue in Shiny (or any other non-interactive session)?

**Comment by cstephens32** [comment]
This did not work. I ended up removing the whole do_refresh function and just set it equal to true. This worked to automatically pull the window up to authenticate and did not require any console prompting. It is not a clean solution though. 

ask_refresh <- function(reason, error_message) {
  inform(sprintf("%s. Error message: \n\n", reason))
  inform(error_message$message)
  inform("\n")

  do_refresh <- TRUE

  if (do_refresh & !is.na(do_refresh)) {
    inform("Trying to generate a new token...")
    .fitbitr_token$init_credentials()
  } else {
    abort("No token was found, and a new one was not generated.")
  }

  invisible()
}

**Comment by mrkaye97** [comment]
Hmm, interesting. It looks like setting `default = TRUE` actually _does_ correctly set the flag. but this of course does not mean that your token refresh will actually work. 

Do you have a sense for if the errors you're seeing are the result of a missing token or of a failed refresh?

I ask because I suspect that `fitbitr` actually needs a bit of an overhaul of how it generates (or re-generates) tokens in non-interactive sessions, which would need to happen by setting a refresh token as a secret and then using that refresh token to create the bearer token you'll use to access the API.

**Comment by mrkaye97** [comment]
@cstephens32 closing this with #9 as documented a bit in the readme: after thinking about it more, I don't think that a Shiny app backend is a good application of `fitbitr`. Unfortunately, the Fitbit API doesn't allow you to generate tokens that last long enough to be practical to use in code that's not running on your local -- e.g. in a Shiny app deployed somewhere, in a job running on a server, etc.

**Pull request closed without merging**
